[build]
  publish = "."
  command = "npm install"

[functions]
  directory = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true